export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const SET_CREDENTIALS = 'SET_CREDENTIALS';
export const REMOVE_CREDENTIALS = 'REMOVE_CREDENTIALS';
export const SESSION_EXPIRED = 'SESSION_EXPIRED';

export const GET_WORKERS = 'GET_WORKERS';
export const ADD_WORKER = 'ADD_WORKER';
export const UPDATE_WORKER = 'UPDATE_WORKER';
export const DISABLE_WORKER = 'DISABLE_WORKER';
export const DELETE_WORKER = 'DELETE_WORKER';
export const GET_WORKFLOWS = 'GET_WORKFLOWS';
export const ADD_WORKFLOW = 'ADD_WORKFLOW';
export const UPDATE_WORKFLOW = 'UPDATE_WORKFLOW';
export const DELETE_WORKFLOW = 'DELETE_WORKFLOW';
export const GET_DEPLOYMENTS = 'GET_DEPLOYMENTS';
export const GET_CONFIGS = 'GET_CONFIGS';

export const SAVE_CONFIGS = 'SAVE_CONFIGS';
