package com.robert

enum class LBAlgorithms(val value: String) {
    RANDOM("RANDOM"),
    LEAST_CONNECTION("LEAST_CONNECTION"),
    RESOURCE_BASED("RESOURCE_BASED"),
    ROUND_ROBIN("ROUND_ROBIN"),
    WEIGHTED_RESPONSE_TIME("WEIGHTED_RESPONSE_TIME"),
}
